# Generated by Django 4.2.6 on 2023-11-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('website', models.CharField(blank=True, max_length=400)),
                ('ringtone', models.FileField(blank=True, upload_to='media/ringtones/%Y/%m')),
                ('groups', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contact.group')),
                ('jobs', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contact.job')),
                ('relationships', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contact.relationship')),
            ],
        ),
    ]
