# Generated by Django 4.2.6 on 2023-11-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('website', models.CharField(blank=True, max_length=400)),
                ('ringtone', models.FileField(blank=True, upload_to='media/ringtones/%Y/%m')),
                ('groups', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contact.group')),
                ('jobs', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contact.job')),
                ('relationships', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contact.relationship')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
