# Generated by Django 4.2.6 on 2023-11-09 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_contact_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='jobs',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contact.job'),
        ),
    ]
